"""Add WorkEventCompleted table

Revision ID: 3fc943b023f9
Revises: ad637fd4205e
Create Date: 2025-05-10 22:41:23.749623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc943b023f9'
down_revision: Union[str, None] = 'ad637fd4205e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_events_completed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_name', sa.String(length=15), nullable=False),
    sa.Column('event_code', sa.String(length=127), nullable=False),
    sa.Column('event_performance_number_identifier', sa.Integer(), nullable=False),
    sa.Column('worker_full_name', sa.String(length=255), nullable=False),
    sa.Column('worker_email', sa.String(length=127), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_events_completed')
    # ### end Alembic commands ###
