"""Added Flight model

Revision ID: 65cee9274011
Revises: ad637fd4205e
Create Date: 2025-04-27 23:03:52.798823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65cee9274011'
down_revision: Union[str, None] = 'ad637fd4205e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_name', sa.String(length=10), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('departure_airport', sa.String(length=10), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('arrival_airport', sa.String(length=10), nullable=False),
    sa.Column('flight_name', sa.String(length=10), nullable=False),
    sa.Column('service_class', sa.String(length=1), nullable=False),
    sa.Column('field1', sa.Integer(), nullable=False),
    sa.Column('field2', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    # ### end Alembic commands ###
