"""Added Works Model

Revision ID: 6c30297d7dfa
Revises: 65cee9274011
Create Date: 2025-04-28 09:35:21.335285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c30297d7dfa'
down_revision: Union[str, None] = '65cee9274011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aircraft_code', sa.String(length=15), nullable=False),
    sa.Column('event_code', sa.String(length=511), nullable=False),
    sa.Column('work_package_number_identifier', sa.Integer(), nullable=False),
    sa.Column('work_package_number', sa.String(length=255), nullable=False),
    sa.Column('event_performance_number_identifier', sa.Integer(), nullable=False),
    sa.Column('event_display_description', sa.String(length=511), nullable=False),
    sa.Column('estimated_man_hours', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_events')
    # ### end Alembic commands ###
