"""add age and user fields in user model

Revision ID: 72629ae28d18
Revises: c6c8a32cd03e
Create Date: 2025-04-22 12:40:19.718930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72629ae28d18'
down_revision: Union[str, None] = 'c6c8a32cd03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
