"""add age and user fields in user model

Revision ID: 72629ae28d18
Revises: c6c8a32cd03e
Create Date: 2025-04-22 12:40:19.718930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72629ae28d18'
down_revision: Union[str, None] = 'c6c8a32cd03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

gender_enum = sa.Enum('M', 'F', name='gender')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False))

    gender_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("users", sa.Column("gender", gender_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'age')

    sa.Enum(name="role").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
